[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "SteamAlly"
version = "0.1.0"
description = "Non-Steam games manager for Linux."
authors = [
    {name = "Vaibhav Prakash"}
]
readme = "README.md"
dependencies = [
  "vdf>=3.0",
  "click>=8.3",
  "PyGObject>=3.54",
]
required-python = ">=3.11"

[project.optional-dependencies]
dev = [
  "pytest>=9.0",
  "ruff",
  "pyright",
]

[project.scripts]
steamally = "src.cli.steam_ally:main"
steamally-gui = "src.gui.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src"]
